// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 The sourcevault Authors. All rights reserved.
// ===================================================================================================================================== //
// MP""""""`MM MMP"""""YMM M""MMMMM""M MM"""""""`MM MM'""""'YMM MM""""""""`M M""MMMMM""M MMP"""""""MM M""MMMMM""M M""MMMMMMMM M""""""""M //
// M  mmmmm..M M' .mmm. `M M  MMMMM  M MM  mmmm,  M M' .mmm. `M MM  mmmmmmmM M  MMMMM  M M' .mmmm  MM M  MMMMM  M M  MMMMMMMM Mmmm  mmmM //
// M.      `YM M  MMMMM  M M  MMMMM  M M'        .M M  MMMMMooM M`      MMMM M  MMMMP  M M         `M M  MMMMM  M M  MMMMMMMM MMMM  MMMM //
// MMMMMMM.  M M  MMMMM  M M  MMMMM  M MM  MMMb. "M M  MMMMMMMM MM  MMMMMMMM M  MMMM' .M M  MMMMM  MM M  MMMMM  M M  MMMMMMMM MMMM  MMMM //
// M. .MMM'  M M. `MMM' .M M  `MMM'  M MM  MMMMM  M M. `MMM' .M MM  MMMMMMMM M  MMP' .MM M  MMMMM  MM M  `MMM'  M M  MMMMMMMM MMMM  MMMM //
// Mb.     .dM MMb     dMM Mb       dM MM  MMMMM  M MM.     .dM MM        .M M     .dMMM M  MMMMM  MM Mb       dM M         M MMMM  MMMM //
// MMMMMMMMMMM MMMMMMMMMMM MMMMMMMMMMM MMMMMMMMMMMM MMMMMMMMMMM MMMMMMMMMMMM MMMMMMMMMMM MMMMMMMMMMMM MMMMMMMMMMM MMMMMMMMMMM MMMMMMMMMM //
// ===================================================================================================================================== //
// This program is free software: you can redistribute it and/or modify                                                                  //
// it under the terms of the GNU Affero General Public License as                                                                        //
// published by the Free Software Foundation, either version 3 of the                                                                    //
// License, or (at your option) any later version.                                                                                       //
//                                                                                                                                       //
// This program is distributed in the hope that it will be useful,                                                                       //
// but WITHOUT ANY WARRANTY; without even the implied warranty of                                                                        //
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                                                                         //
// GNU Affero General Public License for more details.                                                                                   //
//                                                                                                                                       //
// You should have received a copy of the GNU Affero General Public License                                                              //
// along with this program.  If not, see <https://www.gnu.org/licenses/>.                                                                //
// ===================================================================================================================================== //

// Package crypto provides KRL (Key Revocation List) generation.
// The KRL format is binary and compatible with OpenSSH ssh-keygen -Q verification.
package crypto

import (
	"bytes"
	"encoding/binary"
	"fmt"
	"time"
)

const (
	krlMagic         = "SSHKRL\n\x00"
	krlFormatVersion = uint32(1)
	// Section type: revocation by certificate serial number list.
	krlSectionCertificates    = byte(1)
	krlSectionCertSerialList  = byte(0x20)
)

// writeSSHString writes a length-prefixed byte slice in SSH wire format.
func writeSSHString(w *bytes.Buffer, data []byte) {
	_ = binary.Write(w, binary.BigEndian, uint32(len(data)))
	w.Write(data)
}

// GenerateKRL produces an OpenSSH-compatible binary Key Revocation List
// from a slice of certificate serial numbers.
// The resulting bytes can be written to disk and used with sshd's RevokedKeys directive.
func GenerateKRL(serials []uint64) ([]byte, error) {
	buf := new(bytes.Buffer)

	// Write KRL header (magic + version + timestamps + flags + reserved + comment).
	buf.WriteString(krlMagic)
	_ = binary.Write(buf, binary.BigEndian, krlFormatVersion)
	now := uint64(time.Now().Unix())
	_ = binary.Write(buf, binary.BigEndian, now) // KRL version (timestamp)
	_ = binary.Write(buf, binary.BigEndian, now) // generation date
	_ = binary.Write(buf, binary.BigEndian, uint64(0)) // flags (reserved)
	writeSSHString(buf, nil)                            // reserved
	writeSSHString(buf, []byte("Generated by SourceVault"))

	// Build the certificate section only if there are serials to revoke.
	var validSerials []uint64
	for _, s := range serials {
		if s != 0 {
			validSerials = append(validSerials, s)
		}
	}

	if len(validSerials) > 0 {
		var sectionData bytes.Buffer

		// Empty CA key means revocation applies globally to all CAs.
		writeSSHString(&sectionData, nil)
		// Reserved field.
		writeSSHString(&sectionData, nil)

		// Append the serial list subsection.
		sectionData.WriteByte(krlSectionCertSerialList)

		var serialsBlob bytes.Buffer
		for _, s := range validSerials {
			_ = binary.Write(&serialsBlob, binary.BigEndian, s)
		}
		writeSSHString(&sectionData, serialsBlob.Bytes())

		// Write the section type byte followed by the length-prefixed section data.
		buf.WriteByte(krlSectionCertificates)
		writeSSHString(buf, sectionData.Bytes())
	}

	if buf.Len() == 0 {
		return nil, fmt.Errorf("KRL generation produced empty output")
	}

	return buf.Bytes(), nil
}
