// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 The sourcevault Authors. All rights reserved.
// ===================================================================================================================================== //
// MP""""""`MM MMP"""""YMM M""MMMMM""M MM"""""""`MM MM'""""'YMM MM""""""""`M M""MMMMM""M MMP"""""""MM M""MMMMM""M M""MMMMMMMM M""""""""M //
// M  mmmmm..M M' .mmm. `M M  MMMMM  M MM  mmmm,  M M' .mmm. `M MM  mmmmmmmM M  MMMMM  M M' .mmmm  MM M  MMMMM  M M  MMMMMMMM Mmmm  mmmM //
// M.      `YM M  MMMMM  M M  MMMMM  M M'        .M M  MMMMMooM M`      MMMM M  MMMMP  M M         `M M  MMMMM  M M  MMMMMMMM MMMM  MMMM //
// MMMMMMM.  M M  MMMMM  M M  MMMMM  M MM  MMMb. "M M  MMMMMMMM MM  MMMMMMMM M  MMMM' .M M  MMMMM  MM M  MMMMM  M M  MMMMMMMM MMMM  MMMM //
// M. .MMM'  M M. `MMM' .M M  `MMM'  M MM  MMMMM  M M. `MMM' .M MM  MMMMMMMM M  MMP' .MM M  MMMMM  MM M  `MMM'  M M  MMMMMMMM MMMM  MMMM //
// Mb.     .dM MMb     dMM Mb       dM MM  MMMMM  M MM.     .dM MM        .M M     .dMMM M  MMMMM  MM Mb       dM M         M MMMM  MMMM //
// MMMMMMMMMMM MMMMMMMMMMM MMMMMMMMMMM MMMMMMMMMMMM MMMMMMMMMMM MMMMMMMMMMMM MMMMMMMMMMM MMMMMMMMMMMM MMMMMMMMMMM MMMMMMMMMMM MMMMMMMMMM //
// ===================================================================================================================================== //

package crypto

import (
	"bytes"
	"testing"
)

func TestGenerateKRL(t *testing.T) {
	serials := []uint64{100, 200, 300}
	krl, err := GenerateKRL(serials)
	if err != nil {
		t.Fatalf("GenerateKRL failed: %v", err)
	}

	if len(krl) == 0 {
		t.Fatal("KRL is empty")
	}

	if !bytes.HasPrefix(krl, []byte("SSHKRL\n\x00")) {
		t.Error("KRL does not have expected magic header")
	}

	// Basic check: KRL should contain "Generated by SourceVault" comment
	if !bytes.Contains(krl, []byte("Generated by SourceVault")) {
		t.Error("KRL should contain the generation comment")
	}
}

func TestGenerateKRL_Empty(t *testing.T) {
	krl, err := GenerateKRL(nil)
	if err != nil {
		t.Fatalf("GenerateKRL failed: %v", err)
	}
	if len(krl) == 0 {
		t.Fatal("KRL should not be empty even with no serials (header only)")
	}
}
